@startuml

sprite $minecraft [16x16/16z] {
JOzP3WCn24EXcdHOpFslsvWigfKFdcsYH8JIyQXSwJ1t7th9p7dQ6PnjMVOLZJZe7b15Pgn-0ZKPo0Zth4ALp7mQoOmIvOXDDViT_t7taNNxtCwTG-Jj_NLx
6T_x9lkap_x1T0g7sh53Fm00
}

@enduml