@startuml

sprite $mumblelink [16x16/16z] {
NOyx4WCn24EB049yxFlVDjZPRQAA1v9cK7q4jtTKesfnlSWejTB5nz7QrU6vEiycCgexAzRUBPez79NDtdj9hQv83ljmsDwPf6E2jKjqDKL-lLagmhRfg817
35xvX61wVDSBpXdkHZWZd0RGwQe-31B4aGW-VpASLm4pksLV
}

@enduml