@startuml

sprite $murmur [16x16/16z] {
NKu13WCX38AQxBXRBlp_jwDrbop3sXP1A_0F1bEhkb916ZhekfW0rYtT2r8k9ByTOpoIIJU_fAivMMokLpJ7VHpjeAh4Pvw5dZCVM0j6uZn3l96c1jxn2FLT
pKVzuIrtxzb3NFiy6VCSFW00
}

@enduml