/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_minecraft_src_mod_MumbleLink */

#ifndef _Included_net_minecraft_src_mod_MumbleLink
#define _Included_net_minecraft_src_mod_MumbleLink
#ifdef __cplusplus
extern "C" {
#endif
#undef net_minecraft_src_mod_MumbleLink_notificationDelay
#define net_minecraft_src_mod_MumbleLink_notificationDelay 100i64
#undef net_minecraft_src_mod_MumbleLink_IS_A_FILE_PATH
#define net_minecraft_src_mod_MumbleLink_IS_A_FILE_PATH 1L
#undef net_minecraft_src_mod_MumbleLink_IS_NOT_A_FILE_PATH
#define net_minecraft_src_mod_MumbleLink_IS_NOT_A_FILE_PATH 0L
/*
 * Class:     net_minecraft_src_mod_MumbleLink
 * Method:    updateLinkedMumble
 * Signature: ([F[F[FLjava/lang/String;Ljava/lang/String;[F[F[FLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_minecraft_src_mod_1MumbleLink_updateLinkedMumble
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jstring, jstring, jfloatArray, jfloatArray, jfloatArray, jstring, jstring);

/*
 * Class:     net_minecraft_src_mod_MumbleLink
 * Method:    initMumble
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_minecraft_src_mod_1MumbleLink_initMumble
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
